import type { JurisdictionLegalKnowledge } from "./types";

export const CANADA_ONTARIO_KNOWLEDGE: JurisdictionLegalKnowledge = {
  consumer: {
    overview: "Consumer disputes in Ontario are governed primarily by the Consumer Protection Act, 2002 (CPA), which covers unfair practices, false representations, unsolicited goods, internet agreements, direct agreements, and time-share agreements. Consumer Protection Ontario (CPCO) is the enforcement body. The Consumer Services Bureau at the Ontario Ministry of Public and Business Service Delivery handles complaints. Courts (Small Claims Court up to $35,000) and the CPCO are the primary dispute resolution avenues. The Limitations Act, 2002 generally provides a 2-year basic limitation period.",
    keyConcepts: [
      "Consumer Protection Act, 2002 (CPA, SO 2002) — primary consumer protection statute",
      "Consumer Protection Ontario (CPCO) — complaint intake and enforcement",
      "Unfair practices — false representation, misleading advertising (CPA s. 14–17)",
      "Cooling-off periods — 10 days for direct agreements and internet agreements in some circumstances",
      "Misleading price advertising — governed by CPA and Competition Act",
      "Limitations Act, 2002 — 2-year basic limitation period; 15-year ultimate limitation",
      "Small Claims Court — up to $35,000 (no lawyers required but permitted)",
      "Sale of Goods Act (Ontario) — implied conditions as to quality and fitness",
    ],
    riskFactors: [
      "No written contract or receipt",
      "Claim past 2-year limitation period",
      "Verbal representations only — no documentary evidence",
      "Business is unlicensed or operating outside Ontario",
      "Consumer signed broad waiver or dispute resolution clause",
      "Amount in dispute is low relative to litigation cost",
    ],
    helpfulFactors: [
      "Written contract, invoice, or receipt",
      "Email or text correspondence confirming representations",
      "Screenshots of advertising or website claims",
      "CPCO complaint filed and acknowledged",
      "Photos or documentation of defective goods or services",
      "Written demand letter sent before legal action",
    ],
    retrievalSources: ["statute_summary_cpa_ontario", "cpco_guidelines", "small_claims_ontario", "competition_act_federal"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "cpa_ontario", title: "Consumer Protection Act, 2002", url: "https://www.ontario.ca/laws/statute/02c30", section: "Unfair practices, cooling-off periods, internet agreements", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "cpco_main", title: "Consumer Protection Ontario (CPCO)", url: "https://www.consumerprotectionontario.ca/en/home", section: "Consumer complaint resources and enforcement", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "ontario_small_claims", title: "Suing Someone — Small Claims Court (Ontario)", url: "https://www.ontario.ca/page/suing-someone-small-claims-court", section: "Claims up to $35,000", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "limitations_act_ontario", title: "Limitations Act, 2002", url: "https://www.ontario.ca/laws/statute/02l24", section: "Basic limitation period — 2 years from discovery", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  employment: {
    overview: "Employment in Ontario is governed by the Employment Standards Act, 2000 (ESA), which sets minimum standards for hours of work, overtime, wages, termination and severance pay, leaves of absence, and more. The Ministry of Labour administers the ESA. Employees can file claims with the Ministry of Labour's Employment Standards Program. Common law wrongful dismissal claims (for notice beyond ESA minimums) must be pursued in court. The Ontario Human Rights Code prohibits discrimination and harassment in employment. The Occupational Health and Safety Act (OHSA) covers workplace safety and harassment.",
    keyConcepts: [
      "Employment Standards Act, 2000 (ESA) — minimum employment standards",
      "Ministry of Labour — Employment Standards Program (ESA claims)",
      "Common law notice — often exceeds ESA minimums; requires court action",
      "Constructive dismissal — significant changes to job constitute dismissal",
      "Ontario Human Rights Code — discrimination and harassment protections",
      "Human Rights Tribunal of Ontario (HRTO) — human rights complaints",
      "Occupational Health and Safety Act (OHSA) — harassment and safety",
      "Limitations: ESA claims within 2 years of violation; HRTO within 1 year",
    ],
    riskFactors: [
      "Claim filed past limitation period (2 years ESA; 1 year HRTO)",
      "No written employment contract",
      "Verbal termination only, no written confirmation",
      "Employee was terminated 'for cause' — employer claims misconduct",
      "Independent contractor classification may remove ESA protection",
      "No documentation of workplace incidents or harassment",
    ],
    helpfulFactors: [
      "Written employment contract showing terms and role",
      "Pay stubs confirming wage and hours worked",
      "Termination letter or email",
      "Performance reviews — positive history supports wrongful dismissal claim",
      "Emails or texts documenting harassment or workplace conduct",
      "Medical documentation (if health impact is claimed)",
      "Witnesses to termination or workplace incidents",
    ],
    retrievalSources: ["statute_summary_esa_ontario", "mol_claims_process", "hrto_process", "ohsa_harassment_guide"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "esa_ontario", title: "Employment Standards Act, 2000", url: "https://www.ontario.ca/laws/statute/00e41", section: "Termination, severance, overtime, leaves of absence", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "mol_employment_standards", title: "Ontario Ministry of Labour — Employment Standards", url: "https://www.ontario.ca/page/employment-standards-act", section: "Filing a claim with the Employment Standards Program", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "human_rights_code_ontario", title: "Ontario Human Rights Code", url: "https://www.ontario.ca/laws/statute/90h19", section: "Discrimination and harassment in employment", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "hrto_ontario", title: "Human Rights Tribunal of Ontario (HRTO)", url: "https://tribunalsontario.ca/hrto/", section: "Human rights complaint process and timelines", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  landlord_tenant: {
    overview: "Landlord-tenant disputes in Ontario are governed by the Residential Tenancies Act, 2006 (RTA). The Landlord and Tenant Board (LTB) is the administrative tribunal with jurisdiction over most residential tenancy disputes, including evictions, rent increases, maintenance, and lease terminations. Ontario has rent increase guidelines (currently applicable to units built before November 15, 2018). Tenants have strong protections against harassment and unlawful eviction. Applications to the LTB must be filed within 1 year of the event in most cases.",
    keyConcepts: [
      "Residential Tenancies Act, 2006 (RTA) — governing statute for residential tenancies",
      "Landlord and Tenant Board (LTB) — exclusive jurisdiction for residential disputes",
      "Rent increase guideline — annual maximum for qualifying units",
      "N-form notices — standardized forms required for notices (N1-N12, etc.)",
      "Eviction grounds — strictly limited and defined by RTA",
      "Maintenance standard — landlord must maintain property in 'good state of repair'",
      "LTB application limitation: 1 year for most applications",
      "Harassment and interference with reasonable enjoyment — prohibited (RTA s. 22–23)",
    ],
    riskFactors: [
      "LTB application filed past 1-year deadline",
      "No written lease agreement",
      "Rent paid in cash with no receipts or records",
      "Maintenance complaints not documented in writing to landlord",
      "Landlord has N12 (own use) or N13 (demolition) notice — complex proceedings",
      "Improper notice format — LTB may dismiss",
    ],
    helpfulFactors: [
      "Signed lease agreement",
      "Rent receipts or e-transfer records",
      "Written maintenance requests with responses (or lack thereof)",
      "Photos of unit condition issues",
      "Text/email correspondence with landlord",
      "LTB form filed and acknowledged",
    ],
    retrievalSources: ["statute_summary_rta_ontario", "ltb_guide", "rent_increase_guideline_ontario"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "rta_ontario", title: "Residential Tenancies Act, 2006", url: "https://www.ontario.ca/laws/statute/06r17", section: "Tenant and landlord rights, maintenance obligations, rent rules", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "ltb_ontario", title: "Landlord and Tenant Board (LTB)", url: "https://tribunalsontario.ca/ltb/", section: "Applications, hearings, and forms", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  contract: {
    overview: "Contract disputes in Ontario are governed by common law principles (as a common law province) and applicable statutes such as the Sale of Goods Act, the Consumer Protection Act, 2002 (for consumer contracts), and the Electronic Commerce Act. The Limitations Act, 2002 sets a 2-year basic limitation period. Small Claims Court handles disputes up to $35,000. The Ontario Superior Court handles larger matters. Written contracts are generally required for enforceability above certain amounts, and all parties must demonstrate a meeting of the minds, consideration, and intention to create legal relations.",
    keyConcepts: [
      "Common law contract principles — offer, acceptance, consideration, intention",
      "Sale of Goods Act (Ontario) — implied conditions of quality and fitness",
      "Consumer Protection Act, 2002 — additional protection for consumer contracts",
      "Limitations Act, 2002 — 2-year basic limitation period",
      "Small Claims Court — up to $35,000",
      "Material misrepresentation — may allow rescission of contract",
      "Damages — expectation damages (put in position as if contract performed)",
      "Written demand letter — typically required before Small Claims Court filing",
    ],
    riskFactors: [
      "No written contract — verbal agreement harder to prove",
      "Claim past 2-year limitation period",
      "Contract terms are ambiguous or incomplete",
      "Other party claims they performed their obligations",
      "No documented evidence of the breach",
    ],
    helpfulFactors: [
      "Signed written contract specifying each party's obligations",
      "Invoices, purchase orders, or receipts",
      "Emails or texts showing agreement was reached",
      "Evidence of partial performance or payment",
      "Written demand letter sent before legal action",
      "Calculation of actual damages suffered",
    ],
    retrievalSources: ["ontario_contract_law_guide", "sale_of_goods_act_ontario", "small_claims_ontario"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "sale_of_goods_ontario", title: "Sale of Goods Act (Ontario)", url: "https://www.ontario.ca/laws/statute/90s01", section: "Implied conditions as to quality and fitness", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "ontario_small_claims_contract", title: "Suing Someone — Small Claims Court (Ontario)", url: "https://www.ontario.ca/page/suing-someone-small-claims-court", section: "Contract claims up to $35,000", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  human_rights: {
    overview: "Human rights protections in Ontario are provided by the Ontario Human Rights Code. The Human Rights Tribunal of Ontario (HRTO) handles discrimination and harassment complaints in employment, housing, services, contracts, and membership in vocational associations. Protected grounds include race, ancestry, colour, ethnic origin, citizenship, creed, sex, sexual orientation, gender identity, age, disability, family status, marital status, and receipt of public assistance (in housing). HRTO applications must be filed within 1 year of the last discriminatory act.",
    keyConcepts: [
      "Ontario Human Rights Code — primary anti-discrimination statute",
      "Human Rights Tribunal of Ontario (HRTO) — adjudicative body",
      "Protected grounds — disability, race, sex, age, gender identity, religion, and others",
      "Social areas covered — employment, housing, services, contracts, vocational associations",
      "Duty to accommodate — to the point of undue hardship",
      "Systemic vs. direct discrimination",
      "Harassment based on Code grounds — prohibited",
      "Application deadline: 1 year from last act (strict — rarely extended)",
    ],
    riskFactors: [
      "Application filed past 1-year deadline",
      "Respondent has plausible legitimate non-discriminatory explanation",
      "Limited documented evidence of the discriminatory treatment",
      "Applicant was genuinely in breach of workplace rules regardless of disability",
    ],
    helpfulFactors: [
      "Direct evidence of differential treatment on a Code ground",
      "Documented requests for accommodation and employer's response",
      "Medical or other expert evidence supporting disability accommodation need",
      "Witnesses to discriminatory conduct",
      "Pattern of conduct documented in writing",
    ],
    retrievalSources: ["statute_summary_hrto_ontario", "hrto_process", "ohrc_policy_disability"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "human_rights_code_ontario_hr", title: "Ontario Human Rights Code", url: "https://www.ontario.ca/laws/statute/90h19", section: "Prohibited grounds of discrimination", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "hrto_complaints", title: "Human Rights Tribunal of Ontario — How to Apply", url: "https://tribunalsontario.ca/hrto/apply/", section: "Application process and timelines", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "ohrc_policies", title: "Ontario Human Rights Commission — Policies", url: "https://www.ohrc.on.ca/en/ontario-human-rights-policies", section: "Policy guidelines by protected ground", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  landlord_tenant_commercial: {
    overview: "Commercial tenancies in Ontario are not covered by the Residential Tenancies Act. Commercial lease disputes are resolved in Ontario Superior Court or Small Claims Court (under $35,000). Common law and the specific lease terms govern.",
    keyConcepts: ["commercial lease terms", "Ontario Superior Court", "Small Claims Court up to $35,000"],
    riskFactors: ["no written lease", "missed rent creating default", "ambiguous renewal terms"],
    helpfulFactors: ["signed commercial lease", "rent payment records", "written correspondence"],
    retrievalSources: ["ontario_commercial_lease_guide"],
  },

  small_claims: {
    overview: "Ontario's Small Claims Court handles civil disputes up to $35,000. Parties may represent themselves or hire a licensed paralegal or lawyer. The process is designed to be accessible and efficient. Filing fees are based on the amount claimed. A plaintiff's claim, defendant's claim, or counterclaim may be filed. A pre-trial conference is typically scheduled before the hearing. The limitation period for Small Claims is 2 years under the Limitations Act, 2002. A demand letter is strongly recommended before filing.",
    keyConcepts: [
      "Small Claims Court — up to $35,000",
      "Limitation period — 2 years from discovery of claim",
      "Paralegals permitted — licensed paralegal can represent parties",
      "Plaintiff's Claim (Form 7A) — standard way to start a Small Claims action",
      "Defendant can bring a Defendant's Claim (cross-claim)",
      "Pre-trial settlement conference — mandatory before trial",
      "Costs awards — successful party may recover partial costs",
    ],
    riskFactors: [
      "Claim past 2-year limitation period",
      "Defendant in another province — enforcement issues",
      "Claim amount uncertain or difficult to quantify",
      "No written documentation of the dispute",
    ],
    helpfulFactors: [
      "Organized evidence binder with contracts, receipts, correspondence",
      "Written demand letter sent before filing",
      "Clear calculation of damages",
      "Witnesses available to testify",
    ],
    retrievalSources: ["small_claims_ontario", "ontario_court_guide"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ontario_small_claims_guide", title: "Suing Someone — Small Claims Court (Ontario)", url: "https://www.ontario.ca/page/suing-someone-small-claims-court", section: "Overview of small claims process and limits", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "ontario_courts_main", title: "Ontario Courts — Self-Represented Litigants", url: "https://www.ontariocourts.ca/ocj/self-represented-parties/", section: "Resources for self-represented parties", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  insurance: {
    overview: "Insurance disputes in Ontario involving insurers licensed in Ontario fall under the Financial Services Regulatory Authority of Ontario (FSRA). For life and health insurance, the OmbudService for Life and Health Insurance (OLHI) provides dispute resolution. For property and casualty insurance, the General Insurance OmbudService (GIO) is available. The Insurance Act (Ontario) governs policy terms and insurer conduct. Consumers can file complaints with FSRA after exhausting the insurer's internal process.",
    keyConcepts: [
      "Financial Services Regulatory Authority of Ontario (FSRA) — insurance regulator",
      "Insurance Act (Ontario, RSO 1990, c I.8) — governing statute",
      "OLHI — life and health insurance disputes",
      "GIO — general insurance (property, auto, liability) disputes",
      "Duty of good faith — insurer must not unreasonably deny or delay valid claim",
      "Statutory conditions — mandatory conditions in property insurance policies",
      "Limitation period — often specified in the policy (often 1-2 years from loss)",
    ],
    riskFactors: [
      "Claim filed past policy limitation period",
      "Exclusion clause in policy clearly applies",
      "Material misrepresentation at time of application",
      "Insufficient documentation of the loss",
    ],
    helpfulFactors: [
      "Full copy of the insurance policy with all endorsements",
      "Claim denial letter with reasons cited",
      "Documentation of the loss (photos, receipts, reports)",
      "Correspondence with insurer showing timeline",
      "FSRA or OLHI complaint filed",
    ],
    retrievalSources: ["insurance_act_ontario", "fsra_consumer_guide", "olhi_process", "gio_process"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "fsra_ontario", title: "Financial Services Regulatory Authority of Ontario (FSRA)", url: "https://www.fsrao.ca/consumers", section: "Consumer resources and insurance complaints", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "olhi_ontario", title: "OmbudService for Life & Health Insurance (OLHI)", url: "https://olhi.ca/en/", section: "Complaint resolution for life and health insurance", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "gio_ontario", title: "General Insurance OmbudService (GIO)", url: "https://giocanada.org/", section: "Property, auto, and liability insurance disputes", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  financial: {
    overview: "Financial disputes in Ontario involving banks fall under the Financial Consumer Agency of Canada (FCAC) for federally regulated institutions, and FSRA for provincially regulated ones. The Ontario Securities Commission (OSC) handles investment disputes. The Ombudsman for Banking Services and Investments (OBSI) provides free dispute resolution for complaints against banks and investment firms. The Consumer Protection Act, 2002 applies to some consumer credit agreements.",
    keyConcepts: [
      "Financial Consumer Agency of Canada (FCAC) — federal banking practices",
      "Financial Services Regulatory Authority of Ontario (FSRA) — provincial financial regulation",
      "Ombudsman for Banking Services and Investments (OBSI) — free dispute resolution",
      "Ontario Securities Commission (OSC) — investment and securities",
      "Consumer Protection Act, 2002 — covers some consumer credit in Ontario",
      "Limitation period — 2 years under Limitations Act, 2002",
    ],
    riskFactors: [
      "Dispute involves complex investment product",
      "No written documentation of representations made",
      "Claim past limitation period",
      "Signed acknowledgment of risks",
    ],
    helpfulFactors: [
      "Account statements or transaction records",
      "Signed agreements or product disclosure documents",
      "Correspondence showing representations made",
      "OBSI complaint filed",
    ],
    retrievalSources: ["fcac_banking_rights", "fsra_consumer_guide", "obsi_process", "osc_investor_guide"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "fcac_banking", title: "Financial Consumer Agency of Canada (FCAC)", url: "https://www.canada.ca/en/financial-consumer-agency.html", section: "Banking rights and complaint process", jurisdiction: "Canada (Federal)", dateVerified: "2025-04-01" },
      { id: "obsi_canada", title: "Ombudsman for Banking Services and Investments (OBSI)", url: "https://www.obsi.ca/en/", section: "Bank and investment complaints", jurisdiction: "Canada (Federal)", dateVerified: "2025-04-01" },
    ],
  },

  personal_injury: {
    overview: "Personal injury claims in Ontario are governed by common law (negligence) for non-automobile claims, and by the Insurance Act and SABS (Statutory Accident Benefits Schedule) for automobile accident claims. For slip-and-fall and similar claims, the Occupiers' Liability Act, R.S.O. 1990 applies. The basic limitation period is 2 years under the Limitations Act, 2002. For automobile accidents, accident benefit claims must generally be filed within 7 days with the insurer, and tort claims within 2 years.",
    keyConcepts: [
      "Occupiers' Liability Act (Ontario) — duty of care for property owners",
      "Negligence — must prove duty, breach, causation, damage",
      "Insurance Act / SABS — statutory accident benefits for auto accidents",
      "2-year limitation period for personal injury claims",
      "Automobile accidents — no-fault accident benefits plus potential tort action",
      "Product liability — under common law negligence and Sale of Goods Act",
    ],
    riskFactors: [
      "Claim past 2-year limitation period",
      "Causation disputed",
      "Contributory negligence — plaintiff partially at fault",
      "Automobile accident — injury does not meet 'serious and permanent' threshold for full tort recovery",
      "No medical documentation of injury",
    ],
    helpfulFactors: [
      "Medical records and physician reports",
      "Incident report filed at time of event",
      "Photos of the scene and injury",
      "Independent witness statements",
      "Documentation of lost wages and expenses",
    ],
    retrievalSources: ["occupiers_liability_act_ontario", "sabs_guide", "personal_injury_ontario_guide"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "occupiers_liability_ontario", title: "Occupiers' Liability Act (Ontario)", url: "https://www.ontario.ca/laws/statute/90o02", section: "Duty of care of occupiers to visitors", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "ontario_court_personal_injury", title: "Ontario Courts — Civil Claims", url: "https://www.ontario.ca/page/going-superior-court-civil", section: "Personal injury claims procedure", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  privacy_data: {
    overview: "Privacy in Ontario's private sector is primarily governed by the federal Personal Information Protection and Electronic Documents Act (PIPEDA) for provincially regulated organizations, as Ontario does not have its own substantially similar private sector privacy legislation. The federal Privacy Commissioner of Canada investigates PIPEDA complaints. Public sector privacy in Ontario falls under the Freedom of Information and Protection of Privacy Act (FIPPA) and the Municipal Freedom of Information and Protection of Privacy Act (MFIPPA).",
    keyConcepts: [
      "PIPEDA (federal) — applies to Ontario private sector organizations",
      "Office of the Privacy Commissioner of Canada — PIPEDA complaints",
      "Freedom of Information and Protection of Privacy Act (FIPPA) — Ontario public sector",
      "Data breach notification — mandatory under PIPEDA for significant risk of harm",
      "Right of access — individuals can request their personal information",
      "Limitation: complaint to Privacy Commissioner within reasonable time; civil court 2 years",
    ],
    riskFactors: [
      "Organizational privacy policy clearly disclosed the data use",
      "No documented harm from the breach",
      "Government entity involved — different legislation applies",
    ],
    helpfulFactors: [
      "Privacy policy or terms showing what was agreed to",
      "Breach notification letter received",
      "Evidence of actual harm from the breach",
      "Privacy Commissioner complaint acknowledged",
    ],
    retrievalSources: ["pipeda_guide", "opc_complaint_process", "fippa_ontario"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "opc_canada", title: "Office of the Privacy Commissioner of Canada (OPC)", url: "https://www.priv.gc.ca/en/report-a-concern/", section: "Filing a privacy complaint", jurisdiction: "Canada (Federal)", dateVerified: "2025-04-01" },
      { id: "ipc_ontario", title: "Information and Privacy Commissioner of Ontario (IPC)", url: "https://www.ipc.on.ca/en", section: "Privacy complaints under FIPPA/MFIPPA", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },

  other: {
    overview: "Ontario's civil law framework provides remedies for most civil disputes through the courts. Small Claims Court handles matters up to $35,000. The Ontario Superior Court of Justice handles larger matters. The 2-year basic limitation period under the Limitations Act, 2002 applies to most civil claims. Various administrative tribunals (HRTO, LTB, WSIB, etc.) handle specific subject areas.",
    keyConcepts: [
      "Limitations Act, 2002 — 2-year basic limitation; 15-year ultimate",
      "Small Claims Court — up to $35,000",
      "Ontario Superior Court of Justice — larger civil claims",
      "ADR — mediation available for many civil disputes",
      "Various administrative tribunals for specific topics",
    ],
    riskFactors: [
      "Unclear legal basis for the claim",
      "Claim past 2-year limitation",
      "Damages difficult to calculate",
    ],
    helpfulFactors: [
      "Written documentation of the core dispute",
      "Clear timeline with dates",
      "Written demand letter before proceeding",
    ],
    retrievalSources: ["ontario_courts_guide", "limitations_act_ontario"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ontario_courts_general", title: "Ontario Courts — Overview", url: "https://www.ontario.ca/page/ontario-courts", section: "General court navigation and process", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
      { id: "limitations_act_ontario_general", title: "Limitations Act, 2002", url: "https://www.ontario.ca/laws/statute/02l24", section: "Basic and ultimate limitation periods", jurisdiction: "Ontario, Canada", dateVerified: "2025-04-01" },
    ],
  },
};
