import type { JurisdictionLegalKnowledge } from "./types";

export const CANADA_QUEBEC_KNOWLEDGE: JurisdictionLegalKnowledge = {
  consumer: {
    overview: "Consumer disputes in Quebec are governed by the Loi sur la protection du consommateur (LPC), one of the most protective consumer statutes in North America. The LPC applies to contracts between merchants and consumers and covers areas such as misrepresentation, cooling-off periods, and unfair practices. The Office de la protection du consommateur (OPC) enforces these protections. Quebec's civil law system (Civil Code of Quebec — CCQ) also shapes how contract terms are interpreted, often giving priority to the weaker party's reasonable expectations.",
    keyConcepts: [
      "Loi sur la protection du consommateur (LPC) — applies to most consumer contracts",
      "Office de la protection du consommateur (OPC) — complaint intake and enforcement",
      "Civil Code of Quebec (CCQ) — governs obligations and contract interpretation",
      "Cooling-off rights — generally 10 days for certain contracts (timeshares, direct sales)",
      "Implied warranty (garantie légale) — applies to goods even without written warranty",
      "Prescription period — 3 years under CCQ art. 2925 for most civil claims",
      "Small Claims Division (Division des petites créances) — up to $15,000",
      "Prohibition on unfair, misleading or aggressive commercial practices (LPC ss. 215-253)",
    ],
    riskFactors: [
      "No written contract or receipt",
      "Verbal agreements only (difficult to prove)",
      "Claim may be time-barred (past 3 years from discovery)",
      "Merchant not a 'merchant' under LPC — may remove LPC protections",
      "Consumer signed broad waiver or arbitration clause",
      "Damage amount is disputed or undocumented",
    ],
    helpfulFactors: [
      "Written contract, receipt, or order confirmation",
      "Email or text correspondence showing representations made",
      "Clear timeline of events with dates",
      "OPC complaint already filed (creates official record)",
      "Photos or documentation of defective product or service failure",
      "Witnesses to representations made at time of sale",
    ],
    retrievalSources: ["statute_summary_lpc", "opc_guidelines", "ccq_obligations", "small_claims_guide_qc"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "lpc_quebec", title: "Consumer Protection Act (Loi sur la protection du consommateur — LPC)", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/P-40.1", section: "Unfair practices, cooling-off rights, implied warranty", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "opc_quebec", title: "Office de la protection du consommateur (OPC)", url: "https://www.opc.gouv.qc.ca/en/consumer/", section: "Consumer complaints and enforcement", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "small_claims_qc", title: "Small Claims Division — Court of Quebec", url: "https://www.justice.gouv.qc.ca/en/tribunaux-et-organismes/cour-du-quebec/les-divisions/la-division-des-petites-creances/", section: "Claims up to $15,000", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "ccq_obligations", title: "Civil Code of Quebec — Book on Obligations", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/CCQ-1991", section: "Contract formation and consumer protection principles", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  employment: {
    overview: "Employment in Quebec is governed primarily by the Loi sur les normes du travail (LNT) administered by the Commission des normes, de l'équité, de la santé et de la sécurité du travail (CNESST). The LNT sets minimum standards for wages, notice of termination, and working conditions. Quebec's civil law tradition means employment contracts are interpreted under the Civil Code of Quebec, which applies general obligations principles. Psychological harassment at work is specifically prohibited under the LNT. Unionized workplaces follow applicable collective agreements.",
    keyConcepts: [
      "Loi sur les normes du travail (LNT) — minimum standards for all Quebec employees",
      "CNESST — receives complaints about LNT violations (wages, termination, harassment)",
      "Notice of termination — required based on years of service (LNT s. 82)",
      "Constructive dismissal (congédiement déguisé) — recognized under Quebec law",
      "Psychological harassment at work — prohibited under LNT s. 81.18 and s. 81.19",
      "Civil Code of Quebec — governs employment contracts as service contracts (CCQ art. 2085+)",
      "Commission des droits de la personne et des droits de la jeunesse (CDPDJ) — discrimination complaints",
      "Prescription: CNESST complaints generally within 2 years; harassment within 2 years of last event",
    ],
    riskFactors: [
      "No written employment contract",
      "Delay in filing — CNESST complaints have strict time limits",
      "Verbal termination without written confirmation",
      "No documentation of warnings, performance reviews, or incidents",
      "Conflicting versions of events with no written records",
      "Employment through contractor arrangement — may affect LNT coverage",
    ],
    helpfulFactors: [
      "Written employment contract stating role, compensation, and conditions",
      "Pay stubs or records confirming wage amounts",
      "Written termination letter or email",
      "Records of performance reviews — positive or negative",
      "Emails or messages documenting harassment, threats, or workplace conduct",
      "Witnesses to key conversations or incidents",
      "Medical documentation (if stress/health impact is part of the claim)",
    ],
    retrievalSources: ["statute_summary_lnt", "cnesst_guidelines", "ccq_employment", "cdpdj_process"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "lnt_quebec", title: "Act Respecting Labour Standards (Loi sur les normes du travail — LNT)", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/N-1.1", section: "Termination, notice, wages, psychological harassment", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "cnesst_quebec", title: "CNESST — Commission des normes, de l'équité, de la santé et de la sécurité du travail", url: "https://www.cnesst.gouv.qc.ca/en/employer-obligations/labour-standards", section: "Filing a complaint for labour standards violations", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "cdpdj_quebec", title: "Commission des droits de la personne et des droits de la jeunesse (CDPDJ)", url: "https://www.cdpdj.qc.ca/en/complaint", section: "Discrimination complaints in employment", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  landlord_tenant: {
    overview: "Landlord-tenant relations in Quebec are governed primarily by the Civil Code of Quebec (CCQ, arts. 1851–1978), with residential tenancies falling under the Tribunal administratif du logement (TAL), formerly known as the Régie du logement. The TAL has exclusive jurisdiction over most residential tenancy disputes including eviction, rent increases, maintenance, and lease termination. Tenants in Quebec have some of the strongest protections in Canada, including strict rules on lease transfers, eviction grounds, and rent increase limits.",
    keyConcepts: [
      "Tribunal administratif du logement (TAL) — exclusive forum for residential tenancy disputes",
      "Civil Code of Quebec (CCQ arts. 1851–1978) — governs rental agreements",
      "Standard lease form (bail type) — mandatory for most residential rentals",
      "Rent increase rules — landlord must give proper written notice; TAL approval may be required",
      "Eviction grounds — strictly limited (repossession by owner, major renovations)",
      "Lease transfer — tenant has right to transfer lease to another person (CCQ art. 1870)",
      "Maintenance obligations — landlord must maintain property in good condition (CCQ art. 1854)",
      "Prescription: TAL complaints generally within 1 year for many violations",
    ],
    riskFactors: [
      "No written lease or non-standard lease terms",
      "TAL complaint filed past the 1-year prescription",
      "Rent paid in cash with no receipts",
      "No documentation of maintenance requests or communications with landlord",
      "Disputed facts about the condition of the unit",
      "Notice defects — improper format or timing",
    ],
    helpfulFactors: [
      "Signed lease agreement (especially the standard provincial lease form)",
      "Rent receipts or proof of payment",
      "Written maintenance requests with dates",
      "Photos of property condition at entry and at dispute",
      "Correspondence with landlord (emails, texts, letters)",
      "TAL acknowledgement of prior complaints",
    ],
    retrievalSources: ["statute_summary_ccq_rental", "tal_process_guide", "standard_lease_info"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "tal_quebec", title: "Tribunal administratif du logement (TAL)", url: "https://www.tal.gouv.qc.ca/en", section: "Residential lease disputes, rent reduction, evictions", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "ccq_rental", title: "Civil Code of Quebec — Lease of a Dwelling", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/CCQ-1991", section: "Arts. 1851–1978 — residential lease obligations", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  contract: {
    overview: "Contract disputes in Quebec are governed by the Civil Code of Quebec (CCQ), which establishes a comprehensive framework for contracts and obligations. Unlike common law provinces, Quebec uses a civil law system where contracts are interpreted based on the shared intent of the parties and general principles of good faith (CCQ art. 1375). Consumer contracts also benefit from LPC protections. Written contracts provide the clearest evidence, but verbal contracts can be enforceable for amounts under $1,500.",
    keyConcepts: [
      "Civil Code of Quebec (CCQ arts. 1378–1707) — governing law for contracts and obligations",
      "Good faith obligation — parties must act in good faith in performance and enforcement (CCQ art. 1375)",
      "Principle of autonomy of will — parties are generally free to set their own terms",
      "Written vs. oral contracts — written preferred for evidentiary purposes; oral enforceable for small amounts",
      "Remedies: performance, resolution of contract, damages (CCQ arts. 1590–1625)",
      "Prescription period — 3 years for personal actions (CCQ art. 2925)",
      "LPC may supplement if one party is a consumer",
      "Small claims — up to $15,000; no lawyers allowed",
    ],
    riskFactors: [
      "No written contract — reliance on verbal agreement is difficult to prove",
      "Ambiguous or incomplete written terms",
      "Claim past the 3-year prescription period",
      "Other party claims contract was never formed (no meeting of the minds)",
      "Force majeure or impossibility argument by the other side",
    ],
    helpfulFactors: [
      "Signed written contract clearly stating obligations of each party",
      "Invoices, receipts, or purchase orders confirming the transaction",
      "Emails or texts showing agreement was reached",
      "Evidence of performance (partial delivery, payment made)",
      "Written demand letter sent before legal action",
    ],
    retrievalSources: ["statute_summary_ccq_obligations", "ccq_contracts_chapter", "small_claims_guide_qc"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ccq_contracts_qc", title: "Civil Code of Quebec — Obligations and Contracts", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/CCQ-1991", section: "Arts. 1371–1707 — formation, performance and dissolution of contracts", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "small_claims_qc_contract", title: "Small Claims Division — Court of Quebec", url: "https://www.justice.gouv.qc.ca/en/tribunaux-et-organismes/cour-du-quebec/les-divisions/la-division-des-petites-creances/", section: "Contract disputes up to $15,000", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  human_rights: {
    overview: "Human rights protections in Quebec are provided by the Charte des droits et libertés de la personne (Quebec Charter), administered by the Commission des droits de la personne et des droits de la jeunesse (CDPDJ). The Quebec Charter applies to employment, housing, goods and services, and public accommodation. It prohibits discrimination on grounds including race, colour, sex, pregnancy, sexual orientation, gender identity, civil status, age, religion, language, political conviction, social condition, and disability. Complaints to CDPDJ must generally be filed within 2 years.",
    keyConcepts: [
      "Charte des droits et libertés de la personne (Quebec Charter) — primary anti-discrimination law",
      "Commission des droits de la personne et des droits de la jeunesse (CDPDJ) — complaint intake",
      "Protected grounds — race, sex, disability, religion, sexual orientation, age, social condition, and others",
      "Duty to accommodate — to the point of undue hardship",
      "Systemic vs. direct discrimination",
      "Harassment based on prohibited grounds — prohibited",
      "Prescription: generally 2 years from last discriminatory act",
      "Tribunal des droits de la personne — adjudicates referred complaints",
    ],
    riskFactors: [
      "Complaint filed past 2-year prescription period",
      "Discrimination difficult to prove — no direct evidence or admission",
      "Employer can demonstrate legitimate non-discriminatory reason",
      "Complainant contributed to the situation or delayed reporting",
    ],
    helpfulFactors: [
      "Direct or comparative evidence of differential treatment",
      "Documented pattern of conduct toward the complainant",
      "Witnesses who observed the discriminatory treatment",
      "Medical or expert evidence of impact (disability claims)",
      "Records of accommodation requests and responses",
    ],
    retrievalSources: ["statute_summary_qc_charter", "cdpdj_process", "tribunal_droit_personne"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "charter_qc", title: "Charter of Human Rights and Freedoms (Quebec)", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/C-12", section: "Prohibited grounds of discrimination and harassment", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "cdpdj_complaint", title: "CDPDJ — File a Complaint", url: "https://www.cdpdj.qc.ca/en/complaint", section: "Process for discrimination and harassment complaints", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  landlord_tenant_commercial: {
    overview: "Commercial tenancies in Quebec are governed by the Civil Code of Quebec and the terms of the lease. The TAL does not cover commercial leases — commercial disputes must generally be resolved in civil court. Commercial tenants have fewer statutory protections than residential tenants.",
    keyConcepts: ["Civil Code of Quebec", "commercial lease terms", "Superior Court jurisdiction"],
    riskFactors: ["no written lease", "ambiguous renewal terms", "missed rent creating default"],
    helpfulFactors: ["signed commercial lease", "rent payment records", "written correspondence with landlord"],
    retrievalSources: ["ccq_commercial_leases", "superior_court_qc"],
  },

  small_claims: {
    overview: "Quebec's Division des petites créances (Small Claims Division) of the Court of Quebec handles claims up to $15,000. Parties represent themselves — lawyers are not permitted to appear in most cases. The process is designed to be accessible, informal, and fast. Filing fees are low. Cases are decided by a judge who may seek mediation first. Prescription for most civil claims is 3 years under CCQ.",
    keyConcepts: [
      "Division des petites créances — Court of Quebec",
      "Maximum claim: $15,000",
      "No lawyers allowed for parties (self-represented proceedings)",
      "Written demand before filing strongly recommended",
      "Prescription: 3 years for most civil claims (CCQ art. 2925)",
      "Mediation may be offered before hearing",
    ],
    riskFactors: [
      "Claim exceeds $15,000 — must proceed in regular civil court",
      "Opposing party files a counter-claim",
      "Weak documentation of the basis for the claim",
      "Claim is past the 3-year prescription",
    ],
    helpfulFactors: [
      "Organized documentation of the claim with supporting evidence",
      "Written demand letter sent before filing",
      "Clear calculation of damages requested",
      "Receipts, contracts, or other proof of obligation",
    ],
    retrievalSources: ["small_claims_guide_qc", "court_of_quebec_procedures"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "small_claims_qc_general", title: "Small Claims Division — Court of Quebec", url: "https://www.justice.gouv.qc.ca/en/tribunaux-et-organismes/cour-du-quebec/les-divisions/la-division-des-petites-creances/", section: "General small claims process and fee schedule", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  insurance: {
    overview: "Insurance disputes in Quebec are governed by the Insurance Act (CQLR c. A-32), the Civil Code of Quebec, and applicable policy terms. The Autorité des marchés financiers (AMF) regulates insurance companies. Consumers can file complaints with their insurer's internal ombudsman and then escalate to the AMF or civil courts. The AMF's OmbudService for Life and Health Insurance (OLHI) or General Insurance OmbudService (GIO) may also assist.",
    keyConcepts: [
      "Insurance Act (Quebec) — CQLR c. A-32",
      "Autorité des marchés financiers (AMF) — insurance regulator",
      "OLHI (OmbudService for Life & Health Insurance) and GIO (General Insurance OmbudService)",
      "Policy interpretation — ambiguities construed in favour of insured",
      "Duty to act in good faith in claims handling",
      "Prescription: generally 3 years for insurance claims under CCQ",
    ],
    riskFactors: [
      "Claim filed past the prescription deadline",
      "Policy exclusion clearly applies",
      "Material misrepresentation at time of application",
      "Insufficient documentation of the loss or damage claimed",
    ],
    helpfulFactors: [
      "Insurance policy showing coverage terms",
      "Denial letter identifying specific policy provision relied on",
      "Evidence of the loss or damage claimed",
      "Correspondence with insurer showing timeline of claim handling",
    ],
    retrievalSources: ["amf_consumer_guide", "insurance_act_qc", "olhi_process", "gio_process"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "amf_quebec", title: "Autorité des marchés financiers (AMF) — Consumer Resources", url: "https://lautorite.qc.ca/en/general-public/", section: "Insurance complaints and financial services oversight", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "olhi_quebec", title: "OmbudService for Life & Health Insurance (OLHI)", url: "https://olhi.ca/en/", section: "Life and health insurance dispute resolution", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  financial: {
    overview: "Financial disputes in Quebec involving banks and financial institutions are regulated federally under the Financial Consumer Agency of Canada Act (FCAC Act) and provincially by the Autorité des marchés financiers (AMF) for securities, insurance, and other financial products. Unauthorized charges, unfair banking practices, and misrepresentation in financial products may give rise to complaints. Federally regulated banks fall under FCAC; provincially regulated institutions fall under AMF.",
    keyConcepts: [
      "Autorité des marchés financiers (AMF) — provincial financial regulator",
      "Financial Consumer Agency of Canada (FCAC) — federal banking practices",
      "LPC may apply to consumer credit agreements in Quebec",
      "Prescription: generally 3 years under CCQ",
      "Credit reporting — Equifax and TransUnion; dispute process available",
    ],
    riskFactors: [
      "Dispute involves a complex financial product",
      "No written documentation of the representation made",
      "Claim past the prescription period",
      "Contractual arbitration clause limits court access",
    ],
    helpfulFactors: [
      "Account statements showing the disputed transactions",
      "Signed agreements or product disclosure documents",
      "Correspondence showing representations made",
      "FCAC or AMF complaint acknowledgement",
    ],
    retrievalSources: ["amf_consumer_guide", "fcac_banking_rights", "ccq_credit_contracts"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "amf_financial_qc", title: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/en/general-public/", section: "Financial products and investment complaints", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "fcac_banking_qc", title: "Financial Consumer Agency of Canada (FCAC)", url: "https://www.canada.ca/en/financial-consumer-agency.html", section: "Bank complaints and consumer rights", jurisdiction: "Canada (Federal)", dateVerified: "2025-04-01" },
    ],
  },

  personal_injury: {
    overview: "Personal injury claims in Quebec are shaped by the No-Fault automobile accident regime (SAAQ — Société de l'assurance automobile du Québec) and the Civil Code of Quebec for non-auto injuries. For injuries caused by someone's fault, the CCQ requires proving fault, damage, and causal link (CCQ art. 1457). Product liability falls under LPC and CCQ. The prescription period is 3 years (CCQ art. 2925). Note: automobile accident compensation in Quebec is exclusively through SAAQ — no civil action against the at-fault driver is allowed for bodily injury.",
    keyConcepts: [
      "Civil Code of Quebec art. 1457 — civil liability (fault, damage, causal link)",
      "SAAQ — no-fault auto accident compensation (bodily injury only through SAAQ)",
      "Prescription: 3 years for personal injury claims (CCQ art. 2925)",
      "Product liability — LPC art. 53 (safety of goods) + CCQ art. 1468",
      "Occupier's liability — CCQ art. 1465 (liability of property owner/occupier)",
      "Medical expenses, pain and suffering, lost income — recoverable in civil court (non-auto)",
    ],
    riskFactors: [
      "Claim past 3-year prescription period",
      "Causation link is disputed or unclear",
      "Automobile accident — bodily injury compensation is through SAAQ exclusively",
      "No independent witnesses or medical documentation",
      "Contributory fault may reduce damages",
    ],
    helpfulFactors: [
      "Medical records and physician reports documenting the injury",
      "Incident report filed at the time of the event",
      "Photos of the scene and the injury",
      "Witness statements",
      "Documentation of expenses incurred",
    ],
    retrievalSources: ["ccq_civil_liability", "saaq_compensation", "lpc_product_safety"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ccq_civil_liability_qc", title: "Civil Code of Quebec — Civil Liability", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/CCQ-1991", section: "Arts. 1457–1481 — general principles of civil liability", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "saaq_qc", title: "Société de l'assurance automobile du Québec (SAAQ)", url: "https://saaq.gouv.qc.ca/en/", section: "No-fault auto accident compensation", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  privacy_data: {
    overview: "Privacy in Quebec is governed by Act 25 (Law 25 — loi modernisant des dispositions législatives en matière de protection des renseignements personnels), which came into full force in September 2023. Act 25 significantly strengthens privacy requirements for businesses in Quebec, including mandatory breach notification, privacy impact assessments, and data subject rights. The Commission d'accès à l'information (CAI) is the provincial regulator. Federally, PIPEDA (now supplemented by the Consumer Privacy Protection Act) may also apply.",
    keyConcepts: [
      "Act 25 (Law 25) — modernized Quebec private sector privacy law",
      "Commission d'accès à l'information (CAI) — Quebec privacy regulator",
      "Data breach notification — mandatory under Act 25 for serious injury risk",
      "Right of access and correction — individuals can request their personal information",
      "Privacy by default — organizations must use strictest privacy settings by default",
      "Prescription: 3 years under CCQ for civil claims",
    ],
    riskFactors: [
      "No documented data breach notification from the organization",
      "Claim involves federal government — different legislation applies",
      "Organizational policy clearly discloses the data use",
      "No harm (injury) from the privacy breach can be demonstrated",
    ],
    helpfulFactors: [
      "Privacy policy or terms of service showing what was agreed to",
      "Breach notification received",
      "Evidence of actual harm from the privacy breach",
      "CAI complaint filed and acknowledged",
    ],
    retrievalSources: ["act25_summary", "cai_complaint_process", "pipeda_reference"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "cai_quebec", title: "Commission d'accès à l'information du Québec (CAI)", url: "https://www.cai.gouv.qc.ca/en/", section: "Privacy complaints under Act 25 (Law 25)", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "law25_qc", title: "Act to modernize legislative provisions as regards the protection of personal information (Law 25)", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/P-39.1", section: "Personal data rights and breach obligations", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },

  other: {
    overview: "For disputes not falling within a specific legal category, Quebec civil law provides general principles under the Civil Code of Quebec. Most civil claims are subject to a 3-year prescription period (CCQ art. 2925). The Division des petites créances handles claims up to $15,000 without lawyers. The Court of Quebec and Superior Court handle larger matters. The OPC and CNESST handle specific consumer and employment complaints respectively.",
    keyConcepts: [
      "Civil Code of Quebec — general legal framework",
      "Prescription period: 3 years for most civil claims (CCQ art. 2925)",
      "Small Claims Division (up to $15,000) — no lawyers",
      "Mediation and alternative dispute resolution available",
      "OPC — consumer; CNESST — employment; TAL — housing",
    ],
    riskFactors: [
      "Unclear legal basis for the claim",
      "Claim past the 3-year prescription",
      "Damages are difficult to calculate or prove",
    ],
    helpfulFactors: [
      "Written documentation of the core dispute",
      "Clear timeline of events",
      "Correspondence showing the other party's position",
      "Written demand letter sent before legal action",
    ],
    retrievalSources: ["ccq_general", "court_of_quebec_guide", "mediation_qc"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "court_qc_general", title: "Court of Quebec — General Information", url: "https://www.justice.gouv.qc.ca/en/tribunaux-et-organismes/cour-du-quebec/", section: "Court structure, jurisdiction, and procedures", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
      { id: "ccq_general_qc", title: "Civil Code of Quebec", url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/CCQ-1991", section: "General civil law framework", jurisdiction: "Quebec, Canada", dateVerified: "2025-04-01" },
    ],
  },
};
