import type { JurisdictionLegalKnowledge } from "./types";

export const US_CALIFORNIA_KNOWLEDGE: JurisdictionLegalKnowledge = {
  consumer: {
    overview: "California has some of the strongest consumer protection laws in the United States. Key statutes include the Consumers Legal Remedies Act (CLRA, Civil Code §§ 1750-1784), the Unfair Competition Law (UCL, Business & Professions Code § 17200), and the False Advertising Law (FAL, Business & Professions Code § 17500). The CLRA allows consumers to seek damages, injunctions, punitive damages, and attorney's fees for deceptive practices. The UCL has a 4-year statute of limitations; the CLRA has 3 years. The California Department of Consumer Affairs (DCA) and the CA Attorney General provide additional enforcement. Small Claims Court handles up to $12,500 for individuals.",
    keyConcepts: [
      "Consumers Legal Remedies Act (CLRA, Civil Code §§ 1750-1784) — deceptive practices in consumer transactions",
      "Unfair Competition Law (UCL, B&P Code § 17200) — 4-year limitation; broad unfair/unlawful/deceptive conduct",
      "False Advertising Law (FAL, B&P Code § 17500) — 3-year limitation",
      "California Department of Consumer Affairs (DCA) — complaint intake",
      "Song-Beverly Consumer Warranty Act — California lemon law and implied warranty",
      "Small Claims Court — up to $12,500 for individuals",
      "CLRA demand letter — must send 30 days before filing CLRA lawsuit",
      "Private Attorney General Act (PAGA) — relevant for employment; some UCL overlaps",
    ],
    riskFactors: [
      "No written contract or receipt",
      "Claim past 3 years (CLRA) or 4 years (UCL)",
      "Business claims it disclosed all terms clearly",
      "Consumer signed binding arbitration clause",
      "Damage amount is small relative to litigation cost",
    ],
    helpfulFactors: [
      "Written contract, invoice, or receipt",
      "Email or text showing representations made",
      "Screenshots of advertising claims",
      "CLRA demand letter sent and documented",
      "DCA or CA AG complaint filed",
      "Photos of defective product or documentation of service failure",
    ],
    retrievalSources: ["clra_guide", "ucl_overview", "dca_consumer_guide", "ca_small_claims_guide"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "clra_ca", title: "Consumers Legal Remedies Act (CLRA)", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=1750.&lawCode=CIV", section: "Civil Code §§ 1750–1784 — deceptive practices, damages, attorney's fees", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "ucl_ca", title: "Unfair Competition Law (UCL)", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=17200.&lawCode=BPC", section: "Business & Professions Code § 17200 — unfair, unlawful, or fraudulent business practices", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "dca_ca", title: "California Department of Consumer Affairs (DCA)", url: "https://www.dca.ca.gov/consumers/complaints/", section: "Consumer complaint resources and licensing boards", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "ca_small_claims", title: "California Courts — Small Claims", url: "https://www.courts.ca.gov/selfhelp-smallclaims.htm", section: "Claims up to $12,500 for individuals", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  employment: {
    overview: "California has among the most employee-protective labor laws in the U.S. Key statutes include the Labor Code (wages, hours, overtime), the California Fair Employment and Housing Act (FEHA, Government Code § 12900), and the Private Attorneys General Act (PAGA). The Division of Labor Standards Enforcement (DLSE, also called the Labor Commissioner) handles wage and hour claims. FEHA prohibits discrimination and harassment on numerous grounds and is enforced by the Civil Rights Department (CRD, formerly DFEH). Before suing under FEHA, employees must file with the CRD and obtain a 'right-to-sue' notice. PAGA allows employees to sue on behalf of themselves and other aggrieved employees for Labor Code violations.",
    keyConcepts: [
      "California Labor Code — wages, overtime (1.5x after 8hrs/day; 2x after 12hrs/day), rest and meal breaks",
      "Division of Labor Standards Enforcement (DLSE/Labor Commissioner) — wage claims",
      "California Fair Employment and Housing Act (FEHA, Gov. Code § 12900) — broad discrimination/harassment protections",
      "Civil Rights Department (CRD) — complaint intake and right-to-sue letters for FEHA",
      "PAGA (Lab. Code § 2698) — private enforcement of Labor Code violations; 75% penalties to LWDA",
      "At-will employment — terminable for any non-illegal reason",
      "Wrongful termination in violation of public policy (Tameny claim)",
      "Statutes of limitations: DLSE wage claim 3 years; FEHA complaint with CRD 3 years",
    ],
    riskFactors: [
      "Employee was classified as independent contractor (limits Labor Code coverage)",
      "Claim past statute of limitations",
      "No written record of wage rate agreed upon",
      "Employee signed arbitration agreement — may limit court access",
      "Employer claims at-will termination for legitimate business reasons",
    ],
    helpfulFactors: [
      "Pay stubs showing rate and hours worked",
      "Time records or app records showing actual hours",
      "Written employment agreement",
      "Performance reviews showing positive history",
      "Emails or texts documenting discrimination or harassment",
      "CRD right-to-sue letter obtained",
    ],
    retrievalSources: ["ca_labor_code_guide", "dlse_wage_claim_process", "feha_overview", "crd_complaint_process"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "dlse_ca", title: "Division of Labor Standards Enforcement (DLSE) — Wage Claim", url: "https://www.dir.ca.gov/dlse/howtofilewageclaim.htm", section: "Filing a wage claim with the Labor Commissioner", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "feha_ca", title: "California Fair Employment and Housing Act (FEHA)", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=12900.&lawCode=GOV", section: "Government Code § 12900 — discrimination and harassment in employment", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "crd_ca", title: "California Civil Rights Department (CRD) — File a Complaint", url: "https://calcivilrights.ca.gov/complaintprocess/", section: "Right-to-sue letters and FEHA complaint process", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "paga_ca", title: "Private Attorneys General Act (PAGA) — CA DIR", url: "https://www.dir.ca.gov/Private-Attorneys-General-Act/Private-Attorneys-General-Act.html", section: "Private enforcement of Labor Code violations", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  landlord_tenant: {
    overview: "California residential tenancy law is governed by the California Civil Code (§§ 1940-1954.1), the Tenant Protection Act of 2019 (AB 1482) for rent cap and just cause eviction, and local rent control ordinances in many cities (Los Angeles, San Francisco, Oakland, etc.). The Tenant Protection Act limits annual rent increases to 5% plus local CPI (max 10%) for qualifying units and requires just cause for evictions. Local ordinances may be more protective. Eviction proceedings go through Superior Court (unlawful detainer). Security deposit disputes, habitability issues, and illegal lockouts have specific remedies.",
    keyConcepts: [
      "California Civil Code §§ 1940-1954.1 — residential tenancy rights",
      "Tenant Protection Act of 2019 (AB 1482) — statewide rent cap + just cause eviction for qualifying units",
      "Local rent control ordinances — may be more protective (LA, SF, Oakland, etc.)",
      "Implied warranty of habitability — landlord must maintain livable conditions",
      "Security deposit — max 1 month rent (unfurnished); 2 months (furnished); must return within 21 days",
      "Unlawful detainer — court eviction process; tenant has 5 days to respond",
      "Retaliatory eviction — prohibited under Civil Code § 1942.5",
      "Statute of limitations: habitability 3 years; security deposit 4 years (written); 2 years (oral)",
    ],
    riskFactors: [
      "No written lease — month-to-month with limited protections",
      "Claim past applicable statute of limitations",
      "Rent unpaid — weakens tenant's position",
      "Unit not covered by AB 1482 (built after 2005, single-family homes exempt in some cases)",
      "Local rent control may or may not apply — must verify",
    ],
    helpfulFactors: [
      "Signed lease agreement",
      "Rent payment records (e-transfer, check copies)",
      "Written maintenance requests and landlord responses",
      "Photos of habitability issues",
      "Text/email correspondence with landlord",
      "Notice to landlord with 30-day response period for repairs",
    ],
    retrievalSources: ["ca_civil_code_tenancy", "ab1482_guide", "ca_courts_eviction_guide", "local_rent_control_refs"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ab1482_ca", title: "Tenant Protection Act of 2019 (AB 1482)", url: "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB1482", section: "Statewide rent cap and just-cause eviction protections", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "ca_courts_unlawful_detainer", title: "California Courts — Eviction (Unlawful Detainer)", url: "https://www.courts.ca.gov/selfhelp-eviction.htm", section: "Eviction process, defenses, and timelines", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  contract: {
    overview: "Contract disputes in California are governed by the California Civil Code, the Commercial Code (UCC Article 2 for goods), and common law principles. California courts follow objective contract interpretation, looking at the written terms and extrinsic evidence where allowed. Contracts for goods are governed by the UCC. The statute of limitations is 4 years for written contracts and 2 years for oral contracts. Small Claims Court handles up to $12,500. California courts apply the 'substantial performance' doctrine and will look at the reasonable expectations of the parties.",
    keyConcepts: [
      "California Civil Code §§ 1549-1708 — general contract law",
      "California Commercial Code (UCC) — governs sale of goods",
      "Written contract — 4-year statute of limitations",
      "Oral contract — 2-year statute of limitations",
      "Breach of contract elements: valid contract, performance or excuse, breach, resulting damage",
      "Compensatory damages — expectation damages to put party in position if performed",
      "Specific performance — available for unique goods or real property",
      "Small Claims Court — up to $12,500",
    ],
    riskFactors: [
      "Claim past statute of limitations (4yr written; 2yr oral)",
      "No written contract — difficult to prove oral terms",
      "Ambiguous or incomplete written terms",
      "Other party claims contract was not formed",
      "No documentation of breach",
    ],
    helpfulFactors: [
      "Signed written contract",
      "Invoices, purchase orders, receipts",
      "Emails or texts showing agreement and expectations",
      "Evidence of breach and resulting damage",
      "Written demand letter before legal action",
    ],
    retrievalSources: ["ca_civil_code_contracts", "ca_ucc_goods", "ca_small_claims_guide"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ca_civil_code_contracts", title: "California Civil Code — Contracts", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=1549.&lawCode=CIV", section: "Civil Code §§ 1549–1701 — contract formation and enforcement", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "ca_small_claims_contract", title: "California Courts — Small Claims", url: "https://www.courts.ca.gov/selfhelp-smallclaims.htm", section: "Contract claims up to $12,500", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  human_rights: {
    overview: "California prohibits discrimination and harassment through the Fair Employment and Housing Act (FEHA, Government Code § 12900) and the Unruh Civil Rights Act (Civil Code § 51) for business establishments. FEHA covers employment with 5+ employees and housing. The Civil Rights Department (CRD, formerly DFEH) investigates complaints and issues right-to-sue letters. FEHA protects more grounds than federal law, including: race, religion, national origin, sex, gender identity, sexual orientation, disability, age, pregnancy, marital status, and more. Pre-complaint filing with CRD is required before suing under FEHA (3-year deadline to file with CRD).",
    keyConcepts: [
      "Fair Employment and Housing Act (FEHA, Gov. Code § 12900) — employment, housing, business",
      "Civil Rights Department (CRD) — complaint intake; right-to-sue letters required before court",
      "Unruh Civil Rights Act (Civil Code § 51) — prohibits discrimination by business establishments",
      "Protected categories — broader than federal (includes gender identity, sexual orientation)",
      "Disability — broad definition; includes physical and mental impairments",
      "Duty to engage in interactive process and provide reasonable accommodation",
      "3-year statute of limitations to file with CRD",
    ],
    riskFactors: [
      "CRD complaint not filed within 3 years",
      "Employer has plausible legitimate nondiscriminatory reason",
      "No direct evidence of discriminatory motive",
      "Employee had performance issues independent of protected characteristic",
    ],
    helpfulFactors: [
      "Comparative evidence — similarly situated employees treated differently",
      "Documented accommodation requests and employer responses",
      "Medical documentation (for disability claims)",
      "Witnesses to discriminatory conduct",
      "Written or electronic communications showing bias",
      "CRD right-to-sue letter obtained",
    ],
    retrievalSources: ["feha_guide", "crd_complaint_process", "unruh_act_overview"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "feha_ca_hr", title: "California Fair Employment and Housing Act (FEHA)", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=12900.&lawCode=GOV", section: "Prohibited grounds of discrimination in employment and housing", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "crd_complaint_ca", title: "California Civil Rights Department (CRD)", url: "https://calcivilrights.ca.gov/complaintprocess/", section: "Filing a discrimination complaint and obtaining right-to-sue", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "unruh_ca", title: "Unruh Civil Rights Act", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=51.&lawCode=CIV", section: "Civil Code § 51 — full and equal accommodations in business", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  small_claims: {
    overview: "California Small Claims Court handles civil disputes up to $12,500 for individuals ($6,250 for businesses). Parties represent themselves — attorneys are not allowed to appear in court (though may be consulted outside court). A written demand is strongly recommended before filing. Multiple claims against the same defendant are limited. The statute of limitations depends on the type of claim (4 years written contract, 3 years CLRA, 2 years oral). Judgments can be enforced through wage garnishment, bank levies, or liens.",
    keyConcepts: [
      "Small Claims Court — up to $12,500 for individuals",
      "No attorneys in court — self-represented proceedings",
      "Written demand letter recommended before filing",
      "Defendant can be summoned to appear",
      "Judgment enforcement — wage garnishment, bank levy, property lien",
      "Statute of limitations varies by claim type",
    ],
    riskFactors: [
      "Claim amount exceeds $12,500 — must go to civil court",
      "Claim past statute of limitations",
      "Defendant located out of state — enforcement challenges",
    ],
    helpfulFactors: [
      "Organized documentation of the claim",
      "Written demand sent and documented",
      "Photos, receipts, contracts to support the claim",
      "Calculation of damages clearly set out",
    ],
    retrievalSources: ["ca_small_claims_guide", "ca_courts_self_help"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ca_small_claims_general", title: "California Courts — Small Claims Self-Help", url: "https://www.courts.ca.gov/selfhelp-smallclaims.htm", section: "Small claims process, fees, and limits", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  insurance: {
    overview: "Insurance disputes in California are regulated by the California Department of Insurance (CDI). California has strong bad faith insurance law — insurers who unreasonably deny valid claims can face tort liability beyond the policy limit. The Fair Claims Settlement Practices Regulations require timely claim handling. For health insurance, the California Department of Managed Health Care (DMHC) has jurisdiction over HMOs. Consumers can file complaints with CDI or DMHC and access the Independent Medical Review (IMR) process for health coverage denials.",
    keyConcepts: [
      "California Department of Insurance (CDI) — complaint intake for most insurance",
      "California Department of Managed Health Care (DMHC) — HMO and health plan disputes",
      "Insurance Code § 790.03 — prohibited insurance practices",
      "Fair Claims Settlement Practices Regulations — timely claim handling requirements",
      "Bad faith insurance — Civil Code § 2924; tort liability for unreasonable denial",
      "Independent Medical Review (IMR) — free process for health care denials",
      "Statute of limitations: generally 1 year from loss (check policy); 3 years for bad faith claims",
    ],
    riskFactors: [
      "Claim past policy limitation period",
      "Policy exclusion clearly applies",
      "Misrepresentation at time of application",
      "Insufficient documentation of the loss",
    ],
    helpfulFactors: [
      "Insurance policy with all endorsements",
      "Denial letter citing specific policy language",
      "Documentation of loss (photos, estimates, reports)",
      "Correspondence history with insurer",
      "CDI or DMHC complaint filed",
    ],
    retrievalSources: ["cdi_consumer_guide", "dmhc_consumer_guide", "ca_insurance_bad_faith"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "cdi_ca", title: "California Department of Insurance (CDI) — Consumer Complaint", url: "https://www.insurance.ca.gov/01-consumers/101-help/index.cfm", section: "Filing an insurance complaint with the CA Department of Insurance", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "dmhc_ca", title: "CA Department of Managed Health Care (DMHC)", url: "https://www.dmhc.ca.gov/HealthCareProblems.aspx", section: "Health insurance complaint resolution", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  financial: {
    overview: "Financial disputes in California involving banks fall under the federal Financial Consumer Protection Bureau (CFPB) for federally chartered banks, and the California Department of Financial Protection and Innovation (DFPI) for state-chartered institutions and non-bank financial companies. California's Consumer Financial Protection Law (CFPL) gives DFPI broad authority over financial products. The California Consumer Privacy Act (CCPA) provides data rights in the financial context as well.",
    keyConcepts: [
      "Consumer Financial Protection Bureau (CFPB) — federal complaints about banks, credit cards, mortgages",
      "California Department of Financial Protection and Innovation (DFPI) — state financial regulator",
      "California Consumer Financial Protection Law (CFPL) — broad DFPI authority",
      "California Consumer Privacy Act (CCPA) — data rights",
      "Statute of limitations: varies (4 years written contract; CFPL varies)",
    ],
    riskFactors: [
      "No written documentation of representations",
      "Claim past statute of limitations",
      "Signed disclosure documents acknowledging risks",
    ],
    helpfulFactors: [
      "Account statements showing disputed transactions",
      "Signed agreements",
      "CFPB or DFPI complaint filed",
      "Correspondence showing representations made",
    ],
    retrievalSources: ["cfpb_complaint_guide", "dfpi_consumer_guide", "ccpa_overview"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "cfpb_ca", title: "Consumer Financial Protection Bureau (CFPB) — Submit a Complaint", url: "https://www.consumerfinance.gov/complaint/", section: "Federal financial institution complaints", jurisdiction: "USA (Federal)", dateVerified: "2025-04-01" },
      { id: "dfpi_ca", title: "California Department of Financial Protection and Innovation (DFPI)", url: "https://dfpi.ca.gov/file-a-complaint/", section: "State financial institution and fintech complaints", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  personal_injury: {
    overview: "Personal injury claims in California are governed by tort law under the Civil Code. California follows a pure comparative negligence system — even if the plaintiff is 99% at fault, they can recover 1% of their damages. The statute of limitations for personal injury is 2 years from the date of injury (Civil Code § 335.1). Product liability claims (strict liability) have the same 2-year period. Government entities require a claim to be filed with the entity within 6 months of the incident before suing.",
    keyConcepts: [
      "Negligence — duty, breach, causation, damages",
      "Pure comparative negligence — reduces recovery proportionally; not a full bar",
      "Civil Code § 335.1 — 2-year statute of limitations for personal injury",
      "Product liability — strict liability for defective products (Greenman v. Yuba Power Products)",
      "Government tort claims — 6-month government claim filing requirement",
      "Medical records — key evidence for injury and causation",
    ],
    riskFactors: [
      "Claim past 2-year statute of limitations",
      "Plaintiff significantly at fault (reduces recovery)",
      "Government entity involved — missed 6-month claim deadline",
      "Causation disputed",
      "Limited or delayed medical treatment",
    ],
    helpfulFactors: [
      "Immediate medical documentation of injury",
      "Incident report filed at time of event",
      "Photos of scene and injury",
      "Independent witness statements",
      "Documentation of lost income and expenses",
    ],
    retrievalSources: ["ca_negligence_guide", "product_liability_ca", "gov_claims_ca"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ca_courts_civil", title: "California Courts — Civil Self-Help", url: "https://www.courts.ca.gov/selfhelp-civil.htm", section: "General civil claims and injury cases", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  privacy_data: {
    overview: "California leads U.S. privacy law. The California Consumer Privacy Act (CCPA), enhanced by the California Privacy Rights Act (CPRA), gives consumers broad rights over their personal data: right to know, right to delete, right to opt-out of sale, right to correct, and right to limit use of sensitive data. Enforcement is by the California Privacy Protection Agency (CPPA). The California data breach notification law (Civil Code § 1798.82) requires prompt notification of breaches. Private right of action available for breaches of certain data types.",
    keyConcepts: [
      "California Consumer Privacy Act (CCPA) / California Privacy Rights Act (CPRA) — consumer data rights",
      "California Privacy Protection Agency (CPPA) — enforcement",
      "Right to know, delete, correct, opt-out of sale/sharing",
      "California data breach notification law (Civil Code § 1798.82) — prompt notification required",
      "Private right of action for data breach of certain personal information",
      "Statute of limitations: 4 years (UCL-based); breach notification within 30 days",
    ],
    riskFactors: [
      "Business qualifies for CCPA exemption (under 25 employees and low revenue)",
      "No documented harm from the breach",
      "Data types involved not covered by private right of action",
    ],
    helpfulFactors: [
      "Privacy policy or terms showing data collection practices",
      "Breach notification letter",
      "Evidence of harm from breach",
      "CCPA opt-out or deletion request with business's response",
      "CPPA complaint filed",
    ],
    retrievalSources: ["ccpa_cpra_guide", "cppa_complaint_process", "ca_breach_notification_law"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "cppa_ca", title: "California Privacy Protection Agency (CPPA)", url: "https://cppa.ca.gov/", section: "CPRA rights enforcement and consumer privacy complaints", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
      { id: "ccpa_ca", title: "California Consumer Privacy Act (CCPA) — California AG", url: "https://oag.ca.gov/privacy/ccpa", section: "Consumer data rights and opt-out enforcement", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },

  other: {
    overview: "California provides a range of civil remedies through its court system. Small Claims Court handles up to $12,500 for individuals. The California Superior Court handles larger civil matters. Statutes of limitations vary by claim type (2 years personal injury, 3 years CLRA, 4 years written contract, etc.). Alternative dispute resolution (mediation, arbitration) is widely used in California.",
    keyConcepts: [
      "Small Claims Court — up to $12,500 for individuals",
      "Statute of limitations varies by claim type",
      "California Superior Court — for larger civil matters",
      "ADR widely used — mediation and arbitration programs",
    ],
    riskFactors: [
      "Unclear legal basis",
      "Claim past statute of limitations",
      "Damages difficult to quantify",
    ],
    helpfulFactors: [
      "Written documentation of the dispute",
      "Clear timeline of events",
      "Written demand letter before proceeding",
    ],
    retrievalSources: ["ca_courts_self_help", "ca_adr_guide"],
    lastVerified: "2025-04-01",
    sources: [
      { id: "ca_courts_general", title: "California Courts — Self-Help Center", url: "https://www.courts.ca.gov/selfhelp.htm", section: "General court navigation and legal resources", jurisdiction: "California, USA", dateVerified: "2025-04-01" },
    ],
  },
};
